# -*- coding: utf-8 -*-
"""Soluçao semaforo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dO76t3Uie0c3O8WFRsN9N94S-KTzq36M
"""

import time
import random

while True:

    vias = [
        random.randint(0, 30),
        random.randint(0, 30)
    ]

    print("\nCarros na Via 1:", vias[0])
    print("Carros na Via 2:", vias[1])

    if vias[0] > vias[1]:
        tempo1 = vias[0] // 2 + 5
        tempo2 = vias[1] // 2 + 5

        print("\n🚦 Via 1 está VERDE por", tempo1, "segundos")
        time.sleep(tempo1)

        print("🚦 Via 2 está VERDE por", tempo2, "segundos")
        time.sleep(tempo2)

    else:
        tempo2 = vias[1] // 2 + 5
        tempo1 = vias[0] // 2 + 5

        print("\n🚦 Via 2 está VERDE por", tempo2, "segundos")
        time.sleep(tempo2)

        print("🚦 Via 1 está VERDE por", tempo1, "segundos")
        time.sleep(tempo1)

    print("\n--- reiniciando ---")